---
    apiVersion: v1
    kind: Service
    metadata:
      name: fortune-service
      namespace: <replace>
      labels:
        app: fortune-service
    spec:
      ports:
      - port: 80
        targetPort: 8080
        name: web
      type: LoadBalancer
      selector:
        app: fortune-app